### ISSUE TITLE
TODO v 1.0

### ISSUE THREAD

**Issue by edo-lab** [edo-lab/ino-tools#1]
- [ ] Check presence of bugs

- [ ] Adding a second module with sonar emitter, that can work undisturbed

- [ ] Integrate communication with the two modules
